name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mitochondria0001/mountmapbeta:latest  # Replace with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull mitochondria0001/mountmapbeta:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull mitochondria0001/mountmapbeta:latest
            sudo docker stop mountmap-app || true
            sudo docker rm mountmap-app || true
            sudo docker run -d --name mountmap-app -p 3005:3000 mitochondria0001/mountmapbeta:latest



# name: Build and Deploy to Docker Hub

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check Out Repo
#       uses: actions/checkout@v2
      
#     - name: Create .env file
#       run: |
#         echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
#         echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
#         echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
#         echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
#         echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
    
#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./Dockerfile
#         push: true
#         tags: mitochondria0001/mountmapbeta:latest  # Replace with your Docker Hub username and repository

#     - name: Verify Pushed Image
#       run: docker pull mitochondria0001/mountmapbeta:latest

#     - name: Deploy to EC2
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: ${{ secrets.SSH_USERNAME }}
#         key: ${{ secrets.SSH_KEY }}
#         script: |
#           sudo docker pull 100xdevs/web-app:latest
#           sudo docker stop web-app || true
#           sudo docker rm web-app || true
#           sudo docker run -d --name web-app -p 3005:3000 100xdevs/web-app:latest



# name: Build and Deploy to Docker Hub

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check Out Repo
#       uses: actions/checkout@v2
#     - name: Create .env file
      
    
#     - name: Log in to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
    
#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./Dockerfile
#         push: true
#         tags: mitochondria0001/mountmapbeta:latest  # Replace with your Docker Hub username and repository

#     - name: Verify Pushed Image
#       run: docker pull mitochondria0001/mountmapbeta:latest  # Replace with your Docker Hub username and repository
